## Solutions (Part One)

### ✔️ **Solutions to Exercise 1**

In [ ]:
scores <- c(75, 80, 82, 90, 70)

mean_score <- mean(scores)      # 79.4
sd_score <- sd(scores)          # ≈ 7.66
max_score <- max(scores)        # 90

mean_score
sd_score
max_score

[1] 79.4

[1] 7.536577

[1] 90

### ✔️ **Solutions to Exercise 2**

In [ ]:
mat <- matrix(1:6, nrow = 2, byrow = TRUE)
#      [,1] [,2] [,3]
# [1,]    1    2    3
# [2,]    4    5    6

value_23 <- mat[2, 3]           # 6
mat_trans <- t(mat)             # Transposed
row1_sum <- sum(mat[1, ])       # 1 + 2 + 3 = 6
print(mat)
value_23
mat_trans
row1_sum

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6


[1] 6

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[1] 6

### ✔️ **Solutions to Exercise 3**

In [ ]:
arr <- array(1:8, dim = c(2, 2, 2))
# 3D array with 2 layers

target_val <- arr[2, 1, 2]      # 6
arr_sum <- sum(arr)            # 36
print(arr)
target_val
arr_sum

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8



[1] 6

[1] 36

## ✔️ Solutions to Exercise 4

In [ ]:
# 1. Assign the value of pi to a variable called `my_pi`
my_pi <- pi

# 2. Calculate the square root of 64
sqrt_val <- sqrt(64)

# 3. Find the logarithm (natural log) of 10
log_val <- log(10)

# 4. Round the number 3.14159 to 3 decimal places
rounded_val <- round(3.14159, 3)

# 5. Use the exp() function to calculate e^2
exp_val <- exp(2)

# Output to verify
my_pi
sqrt_val
log_val
rounded_val
exp_val

[1] 3.141593

[1] 8

[1] 2.302585

[1] 3.142

[1] 7.389056

### ✔️ Solutions to Exercise 5

In [ ]:
# Solution for Exercise 9

temperatures <- c(23.4, 21.8, 24.6, 22.0, 20.9, 25.5, 23.0)

# 1. Calculate the mean temperature
mean_temp <- mean(temperatures)

# 2. Calculate the median temperature
median_temp <- median(temperatures)

# 3. Find the maximum and minimum temperature
max_temp <- max(temperatures)
min_temp <- min(temperatures)

# 4. Find the range (difference between max and min)
range_temp <- max_temp - min_temp

# 5. Calculate the variance
variance_temp <- var(temperatures)

# Output to verify
mean_temp
median_temp
max_temp
min_temp
range_temp
variance_temp

[1] 23.02857

[1] 23

[1] 25.5

[1] 20.9

[1] 4.6

[1] 2.635714

## Solutions (Part Two)

1. **B) `mean()`**

2. **B) 4**

3. **B) `matrix()`**

4. **B) The number of elements**

5. **B) `%*%`**

6. **sd**

7. **1:5**

In [ ]:
c(1,2,3,4,5)

[1] 1 2 3 4 5